version: "3.8"
services:
  keg-node-proxy:
    image: ${KEG_IMAGE_FROM}
    container_name: keg-node-proxy
    tty: true
    stdin_open: true
    networks:
      - keg-hub-net
    build:
      context: /Users/lancetipton/keg-hub/taps/keg-proxy
      dockerfile: /Users/lancetipton/keg-hub/taps/keg-proxy/container/Dockerfile
    environment:
      - DOC_APP_PATH
      - DOC_BUILD_PATH
      - KEG_DOCKER_EXEC
      - KEG_DOCKER_NETWORK
      - KEG_EXEC_CMD
      - KEG_NM_INSTALL
      - KEG_NODE_VERSION
      - KEG_PROXY_HOST
      - NODE_ENV
      - PROXY_INSECURE_PORT
      - PROXY_SECURE_PORT
      - PROXY_DASHBOARD_PORT
      - PROXY_HEALTHCHECK_PORT
    ports:
      - ${PROXY_INSECURE_PORT}:${PROXY_INSECURE_PORT:-80}
      - ${PROXY_SECURE_PORT}:${PROXY_SECURE_PORT:-443}
      - ${PROXY_DASHBOARD_PORT}:${PROXY_DASHBOARD_PORT:-18001}
      - ${PROXY_HEALTHCHECK_PORT}:${PROXY_HEALTHCHECK_PORT:-8080}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - com.keg.env.context=keg-node-proxy
      - com.keg.env.cmd=${KEG_EXEC_CMD}
      - com.keg.env.port=${PROXY_DASHBOARD_PORT}
      - com.keg.path.context=${KEG_CONTEXT_PATH}
      - com.keg.path.container=${DOC_APP_PATH}
      - com.keg.path.compose=${KEG_COMPOSE_DEFAULT}
      - com.keg.path.values=${KEG_VALUES_FILE}
      - com.keg.path.docker=${KEG_DOCKER_FILE}
      - com.keg.proxy.domain=kpy-master
networks:
    keg-hub-net:
        driver: bridge
        name: keg-hub-net
