version: "3.8"
services:
  tap-proxy:
    image: ${KEG_IMAGE_FROM}
    container_name: tap-proxy
    tty: true
    stdin_open: true
    networks:
      - keg-hub-net
    build:
      context: ../
      dockerfile: ./Dockerfile
    environment:
      - DOC_APP_PATH
      - DOC_BUILD_PATH
      - KEG_DOCKER_EXEC
      - KEG_DOCKER_NETWORK
      - KEG_EXEC_CMD
      - KEG_NM_INSTALL
      - KEG_NODE_VERSION
      - KEG_PROXY_HOST
      - KEG_PROXY_SERVER_PORT
      - KEG_PROXY_UPDATE
      - NODE_ENV
    ports:
      - ${KEG_PROXY_SERVER_PORT}:${KEG_PROXY_SERVER_PORT:-80}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
networks:
    keg-hub-net:
        driver: bridge
        name: keg-hub-net
