version: "3.8"
services:
  keg-node-proxy:
    environment:
      - DOC_APP_PATH
      - DOC_BUILD_PATH
      - KEG_DOCKER_EXEC
      - KEG_DOCKER_NETWORK
      - KEG_EXEC_CMD
      - KEG_NM_INSTALL
      - KEG_NODE_VERSION
      - KEG_PROXY_HOST
      - NODE_ENV
    networks:
      - ${KEG_DOCKER_NETWORK}
    ports:
      - ${PROXY_INSECURE_PORT}:${PROXY_INSECURE_PORT:-80}
      - ${PROXY_SECURE_PORT}:${PROXY_SECURE_PORT:-443}
      - ${PROXY_DASHBOARD_PORT}:${PROXY_DASHBOARD_PORT:-18001}
      - ${PROXY_HEALTHCHECK_PORT}:${PROXY_HEALTHCHECK_PORT:-8080}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
networks:
    keg-hub-net:
        driver: bridge
        name: ${KEG_DOCKER_NETWORK:-keg-hub-net}