# Not currently setup, but will be at some point
# Using settings would allow separating keg-cli settings from ENV values
settings: 
  # Turn off adding an injected compose config for tap-proxy
  injectedCompose: true
  # Turn off auto-building the keg-base image
  autoBuildBase: false
  # Turn off auto-creating a tap-proxy sync in develop environments
  autoSync: true
  # Toggle merging the default mutagen sync config with the taps config
  useSyncDefault: false
  # Ensures watchtower won't restart the container when a new image is found (default is true)
  watchTowerEnabled: false
  # Disable auto starting the tap-proxy
  useKegProxy: false
  # Disable calling docker exec on the container after it's started
  useAutoExec: false

env:
  # --- LOCAL ENV CONTEXT --- #
  IMAGE: 'tap-proxy'

  # --- LOCAL ENV CONTEXT --- #
  KEG_CONTEXT_PATH: "{{ cli.taps.tp.path }}"
  ROOT_PATH: {{ cli.taps.tp.path }}
  SRC_PATH: {{ cli.taps.tp.path }}/src
  CONFIGS_PATH: {{ cli.taps.tp.path }}/configs

  # Turn off adding an injected compose config for tap-proxy
  KEG_NO_INJECTED_COMPOSE: true

  # Turn off auto-creating a tap-proxy sync
  KEG_AUTO_SYNC: false

  # Turn off the auto docker exec command after the container is started
  KEG_AUTO_DOCKER_EXEC: false

  KEG_BASE_IMAGE: node:14.7-alpine

  # Turn off auto-building the keg-base image
  KEG_FROM_BASE: false

  # Command to run when the container starts
  KEG_EXEC_CMD: start

  KEG_NODE_IMAGE: node:14.7-alpine
  
  # Set the default image from, even when not being used
  KEG_IMAGE_FROM: ghcr.io/keg-hub/tap-proxy:develop

  # Turn off using the tap-proxy
  KEG_USE_PROXY: false

  # Ensures watchtower won't restart the container when a new image is found (default is true)
  KEG_WATCHTOWER_ENABLED: false
  
  # KEG_PROXY_ALLOWED_ORIGINS: localhost,herkin-develop.local.keghub.io

  # --- PROXY ENV CONTEXT --- #

  KEG_DOCKER_FILE: "{{ cli.taps.tp.path }}/container/Dockerfile"
  KEG_VALUES_FILE: "{{ cli.taps.tp.path }}/container/values.yml"
  KEG_MUTAGEN_FILE: "{{ cli.taps.tp.path }}/container/mutagen.yml"
  KEG_COMPOSE_DEFAULT: "{{ cli.taps.tp.path }}/container/docker-compose.yml"

  # Default location of the tap in the docker container
  DOC_APP_PATH: /keg/tap
  DOR_ROOT_PATH: /keg/tap
  DOC_SRC_PATH: /keg/tap/src
  DOC_CONFIGS_PATH: /keg/tap/configs

  # Default host for the keg proxy
  KEG_PROXY_HOST: local.keghub.io
  KEG_PROXY_SERVER_PORT: 80
  KEG_PROXY_UPDATE: 10000

  # Default docker network
  KEG_DOCKER_NETWORK: keg-hub-net

  # Must be one of debug, panic, fatal, error, warn, info
  PROXY_LOG_LEVEL: error

